# Address failing osx build which started in 0.1.14
# https://conda-forge.org/docs/maintainer/knowledge_base.html#requiring-newer-macos-sdks
macos_min_version:
  - 10.12 # [osx and x86_64]
MACOSX_DEPLOYMENT_TARGET:
  - 10.12 # [osx and x86_64]
CONDA_BUILD_SYSROOT:
  - /opt/MacOSX10.12.sdk        # [osx and x86_64]