{% set name = "ruff" %}
{% set version = "0.14.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9a2e830f075d1a42cd28420d7809ace390832a490ed0966fe373ba288e77aaf4

build:
  number: 0
  skip: true  # [py<37]
  script_env:
    - JEMALLOC_SYS_WITH_LG_PAGE=16

requirements:
  build:
    - python
    - {{ compiler('rust') }}
    - {{ compiler('c') }}  # [linux]
    - make  # [linux]
    - git  # [linux]
    - maturin >=1.0,<2.0
    - cargo-bundle-licenses
  host:
    - python
    - pip
    - maturin >=1.9,<2.0
    - toml
  run:
    - python

test:
  requires:
    - pip
  commands:
    - ruff --help
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
  imports:
    - ruff

about:
  home: https://github.com/astral-sh/ruff
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: An extremely fast Python linter, written in Rust.
  description: |
    An extremely fast Python linter, written in Rust. Ruff can be used to
    replace Flake8 (plus a variety of plugins), isort, pydocstyle, yesqa, and
    even a subset of pyupgrade and autoflake all while executing tens or
    hundreds of times faster than any individual tool.
  dev_url: https://github.com/astral-sh/ruff
  doc_url: https://docs.astral.sh/ruff

extra:
  recipe-maintainers:
    - zanieb
    - messense
    - charliermarsh
