{% set name = "ruff" %}
{% set version = "0.0.203" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9d442bba26e81c1c3cb33b2af08071fcf41f023edb06478dbe402189a0614661

build:
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('rust') }}
    - maturin
    - cargo-bundle-licenses
  host:
    - python
    - pip
    - maturin
    - toml
  run:
    - python

test:
  commands:
    - ruff --help

about:
  home: https://github.com/charliermarsh/ruff
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: An extremely fast Python linter, written in Rust.

  # The remaining entries in this section are optional, but recommended.
  description: |
    An extremely fast Python linter, written in Rust. Ruff can be used to
    replace Flake8 (plus a variety of plugins), isort, pydocstyle, yesqa, and
    even a subset of pyupgrade and autoflake all while executing tens or
    hundreds of times faster than any individual tool.
  dev_url: https://github.com/charliermarsh/ruff

extra:
  recipe-maintainers:
    - charliermarsh
