{% set name = "ruff" %}
{% set version = "0.3.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a067daaeb1dc2baf9b82a32dae67d154d95212080c80435eb052d95da647763d

build:
  number: 0
  missing_dso_whitelist:
    - '$RPATH/ld64.so.1'  # [s390x]

requirements:
  build:
    - python
    - {{ compiler('rust') }}
    - maturin
    - cargo-bundle-licenses
  host:
    - python
    - pip
    - maturin
    - toml
  run:
    - python

test:
  requires:
    - pip
  commands:
    - ruff --help
    - pip check
  imports:
    - ruff

about:
  home: https://github.com/charliermarsh/ruff
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: An extremely fast Python linter, written in Rust.
  description: |
    An extremely fast Python linter, written in Rust. Ruff can be used to
    replace Flake8 (plus a variety of plugins), isort, pydocstyle, yesqa, and
    even a subset of pyupgrade and autoflake all while executing tens or
    hundreds of times faster than any individual tool.
  dev_url: https://github.com/charliermarsh/ruff
  doc_url: https://docs.astral.sh/ruff

extra:
  recipe-maintainers:
    - zanieb
    - messense
    - charliermarsh
